using System.Text;

namespace MultiInherit.Generator;

internal static class CodeEmitter
{
    public static string Emit(ResolvedModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using MultiInherit;");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(model.Namespace);
        if (hasNs) { sb.AppendLine($"namespace {model.Namespace};"); sb.AppendLine(); }

        sb.AppendLine($"partial class {model.ClassName} : IModel, INotifyPropertyChanged");
        sb.AppendLine("{");

        EmitInfrastructure(sb, model);
        EmitClassicalFields(sb, model);
        EmitDelegations(sb, model);
        EmitRelations(sb, model);
        EmitComputedFields(sb, model);
        EmitFieldCatalog(sb, model);
        EmitConstraintDispatcher(sb, model);
        EmitOnchangeDispatcher(sb, model);
        EmitModuleInitializer(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Infrastructure: INotifyPropertyChanged + ModelName ─────────────────

    private static void EmitInfrastructure(StringBuilder sb, ResolvedModel model)
    {
        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine("    protected void OnPropertyChanged(string name)");
        sb.AppendLine("        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));");
        sb.AppendLine();
        sb.AppendLine($"    public static string ModelName => \"{model.ModelName}\";");
        sb.AppendLine();
        sb.AppendLine("    public int Id { get; set; }");
        sb.AppendLine();
    }

    // ── Classical inherited fields ─────────────────────────────────────────

    private static void EmitClassicalFields(StringBuilder sb, ResolvedModel model)
    {
        foreach (var f in model.ClassicallyInheritedFields)
            EmitStoredProperty(sb, f, "Inherited (classical)");
    }

    // ── Delegation ─────────────────────────────────────────────────────────

    private static void EmitDelegations(StringBuilder sb, ResolvedModel model)
    {
        foreach (var del in model.DelegationParents)
        {
            sb.AppendLine($"    // ── Delegation → '{del.ParentModelName}' ──");
            sb.AppendLine($"    public int {del.ForeignKeyName} {{ get; set; }}");
            sb.AppendLine();
            var nav = del.NavigationPropertyName;
            sb.AppendLine($"    private {del.ParentClassName}? _{LowerFirst(nav)};");
            sb.AppendLine($"    public {del.ParentClassName}? {nav}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => _{LowerFirst(nav)};");
            sb.AppendLine($"        set => _{LowerFirst(nav)} = value;");
            sb.AppendLine("    }");
            sb.AppendLine();
            foreach (var f in del.DelegatedFields)
            {
                // La navigation étant nullable, les champs délégués le sont aussi
                var nullable = "?";
                sb.AppendLine($"    // Delegated from {del.ParentModelName}");
                sb.AppendLine($"    public {f.TypeName}{nullable} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {nav}?.{f.PropertyName};");
                if (f.HasSetter) sb.AppendLine($"        set {{ if ({nav} != null) {nav}.{f.PropertyName} = value; }}");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }
    }

    // ── Relational fields ──────────────────────────────────────────────────

    private static void EmitRelations(StringBuilder sb, ResolvedModel model)
    {
        foreach (var rel in model.Relations)
        {
            switch (rel.Kind)
            {
                case RelationKind.Many2one:  EmitMany2one(sb, rel);  break;
                case RelationKind.One2many:  EmitOne2many(sb, rel);  break;
                case RelationKind.Many2many: EmitMany2many(sb, rel); break;
            }
        }
    }

    private static void EmitMany2one(StringBuilder sb, ResolvedRelation rel)
    {
        var label = rel.Label != null ? $" \"{rel.Label}\"" : string.Empty;
        sb.AppendLine($"    // Many2one →{label} '{rel.ComodelName}'  [OnDelete: {rel.OnDelete}]");

        // FK integer property
        var req = rel.Required ? " // Required" : string.Empty;
        sb.AppendLine($"    public int{(rel.Required ? "" : "?")} {rel.ForeignKeyName} {{ get; set; }}{req}");
        sb.AppendLine();

        // Navigation property with lazy backing field
        var navBacking = $"_{LowerFirst(rel.PropertyName)}";
        sb.AppendLine($"    private {rel.ComodelClassName}? {navBacking};");
        sb.AppendLine($"    public partial {rel.ComodelClassName}? {rel.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {navBacking};");
        sb.AppendLine("        set");
        sb.AppendLine("        {");
        sb.AppendLine($"            {navBacking} = value;");
        sb.AppendLine($"            {rel.ForeignKeyName} = value?.Id ?? 0;");
        sb.AppendLine($"            OnPropertyChanged(nameof({rel.PropertyName}));");
        sb.AppendLine($"            OnPropertyChanged(nameof({rel.ForeignKeyName}));");
        sb.AppendLine($"            __TriggerOnchange(nameof({rel.PropertyName}));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitOne2many(StringBuilder sb, ResolvedRelation rel)
    {
        var label = rel.Label != null ? $" \"{rel.Label}\"" : string.Empty;
        sb.AppendLine($"    // One2many →{label} '{rel.ComodelName}' (inverse: {rel.InverseField})");
        sb.AppendLine($"    private ICollection<{rel.ComodelClassName}>? _{LowerFirst(rel.PropertyName)};");
        sb.AppendLine($"    public partial ICollection<{rel.ComodelClassName}> {rel.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => _{LowerFirst(rel.PropertyName)} ??= new List<{rel.ComodelClassName}>();");
        sb.AppendLine($"        set => _{LowerFirst(rel.PropertyName)} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitMany2many(StringBuilder sb, ResolvedRelation rel)
    {
        var label = rel.Label != null ? $" \"{rel.Label}\"" : string.Empty;
        sb.AppendLine($"    // Many2many →{label} '{rel.ComodelName}'");
        sb.AppendLine($"    // Join table: {rel.RelationTable}  ({rel.Column1} ↔ {rel.Column2})");
        sb.AppendLine($"    private ICollection<{rel.ComodelClassName}>? _{LowerFirst(rel.PropertyName)};");
        sb.AppendLine($"    public partial ICollection<{rel.ComodelClassName}> {rel.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => _{LowerFirst(rel.PropertyName)} ??= new List<{rel.ComodelClassName}>();");
        sb.AppendLine($"        set => _{LowerFirst(rel.PropertyName)} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Computed fields ────────────────────────────────────────────────────

    private static void EmitComputedFields(StringBuilder sb, ResolvedModel model)
    {
        foreach (var cf in model.ComputedFields)
        {
            var nullable     = cf.IsNullable ? "?" : "";
            var backingField = $"_{LowerFirst(cf.PropertyName)}";
            var dirtyFlag    = $"_{LowerFirst(cf.PropertyName)}_dirty";
            var depends      = string.Join(", ", cf.DependsOn.Select(d => $"\"{d}\""));

            sb.AppendLine($"    // Computed [{(cf.Store ? "stored" : "non-stored")}]  method: {cf.ComputeMethod}");
            if (cf.DependsOn.Length > 0) sb.AppendLine($"    // Depends on: {string.Join(", ", cf.DependsOn)}");

            sb.AppendLine($"    private {cf.TypeName}{nullable} {backingField};");

            if (!cf.Store)
            {
                sb.AppendLine($"    private bool {dirtyFlag} = true;");
                sb.AppendLine($"    public partial {cf.TypeName}{nullable} {cf.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine("        get");
                sb.AppendLine("        {");
                sb.AppendLine($"            if ({dirtyFlag}) {{ {cf.ComputeMethod}(); {dirtyFlag} = false; }}");
                sb.AppendLine($"            return {backingField};");
                sb.AppendLine("        }");
                sb.AppendLine($"        private set {{ {backingField} = value; }}");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"    public partial {cf.TypeName}{nullable} {cf.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {backingField};");
                sb.AppendLine("        private set");
                sb.AppendLine("        {");
                sb.AppendLine($"            {backingField} = value;");
                sb.AppendLine($"            OnPropertyChanged(nameof({cf.PropertyName}));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            if (cf.DependsOn.Length > 0 && !cf.Store)
                sb.AppendLine($"    private static readonly string[] __{cf.PropertyName}_depends = {{ {depends} }};");
            sb.AppendLine();
        }
    }

    // ── Field catalog + dependency dispatcher ──────────────────────────────

    private static void EmitFieldCatalog(StringBuilder sb, ResolvedModel model)
    {
        // __InvalidateDependents
        sb.AppendLine("    private void __InvalidateDependents(string changedField)");
        sb.AppendLine("    {");
        foreach (var cf in model.ComputedFields.Where(c => !c.Store && c.DependsOn.Length > 0))
        {
            sb.AppendLine($"        if (System.Array.IndexOf(__{cf.PropertyName}_depends, changedField) >= 0)");
            sb.AppendLine($"        {{ _{LowerFirst(cf.PropertyName)}_dirty = true; OnPropertyChanged(nameof({cf.PropertyName})); }}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Static Fields catalog
        sb.AppendLine("    public static class Fields");
        sb.AppendLine("    {");
        foreach (var f in model.OwnFields)
            sb.AppendLine($"        public static readonly ModelFieldInfo {f.PropertyName} = new(\"{f.PropertyName}\", typeof({f.TypeName}), IsComputed: false, IsStored: true);");
        foreach (var cf in model.ComputedFields)
            sb.AppendLine($"        public static readonly ModelFieldInfo {cf.PropertyName} = new(\"{cf.PropertyName}\", typeof({cf.TypeName}), IsComputed: true, IsStored: {cf.Store.ToString().ToLower()});");
        foreach (var rel in model.Relations)
            sb.AppendLine($"        public static readonly ModelFieldInfo {rel.PropertyName} = new(\"{rel.PropertyName}\", typeof({rel.ComodelClassName}), IsComputed: false, IsStored: {(rel.Kind == RelationKind.Many2one ? "true" : "false")});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Constraint dispatcher ──────────────────────────────────────────────

    private static void EmitConstraintDispatcher(StringBuilder sb, ResolvedModel model)
    {
        if (model.ConstraintMethods.Count == 0 && model.SqlConstraints.Count == 0) return;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Runs all [Constrains] methods. Call before saving the record.");
        sb.AppendLine("    /// Throws <see cref=\"ModelValidationException\"/> on the first violation.");
        sb.AppendLine("    /// </summary>");
        // Champs statiques pour éviter une allocation HashSet par appel
        foreach (var cm in model.ConstraintMethods.Where(c => c.Fields.Length > 0))
        {
            var fieldSet = string.Join(", ", cm.Fields.Select(f => $"\"{f}\""));
            sb.AppendLine($"    private static readonly System.Collections.Generic.HashSet<string> ___{cm.MethodName}_fields =");
            sb.AppendLine($"        new System.Collections.Generic.HashSet<string> {{ {fieldSet} }};");
        }

        sb.AppendLine("    public void ValidateConstraints(System.Collections.Generic.IEnumerable<string>? changedFields = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var changed = changedFields?.ToHashSet();");
        foreach (var cm in model.ConstraintMethods)
        {
            if (cm.Fields.Length == 0)
            {
                // Aucun champ déclaré → la contrainte s'exécute toujours
                sb.AppendLine($"        {cm.MethodName}();");
            }
            else
            {
                sb.AppendLine($"        // [{string.Join(", ", cm.Fields)}]");
                sb.AppendLine($"        if (changed == null || ___{cm.MethodName}_fields.Overlaps(changed))");
                sb.AppendLine($"            {cm.MethodName}();");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        if (model.SqlConstraints.Count > 0)
        {
            sb.AppendLine("    /// <summary>SQL constraints declared on this model.</summary>");
            sb.AppendLine("    public static readonly (string Name, string Sql, string Message)[] SqlConstraints =");
            sb.AppendLine("    [");
            foreach (var sc in model.SqlConstraints)
                sb.AppendLine($"        (\"{sc.Name}\", \"{sc.Sql}\", \"{sc.Message}\"),");
            sb.AppendLine("    ];");
            sb.AppendLine();
        }
    }

    // ── Onchange dispatcher ────────────────────────────────────────────────

    private static void EmitOnchangeDispatcher(StringBuilder sb, ResolvedModel model)
    {
        if (model.OnchangeMethods.Count > 0)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Runs all [Onchange] methods whose trigger fields intersect with <paramref name=\"changedFields\"/>.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public void TriggerOnchange(System.Collections.Generic.IEnumerable<string> changedFields)");
            sb.AppendLine("    {");
            sb.AppendLine("        var changed = changedFields.ToHashSet();");
            foreach (var om in model.OnchangeMethods)
            {
                var fieldSet = string.Join(", ", om.Fields.Select(f => $"\"{f}\""));
                sb.AppendLine($"        if (new System.Collections.Generic.HashSet<string> {{ {fieldSet} }}.Overlaps(changed)) {om.MethodName}();");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            // Private helper called from Many2one setters and stored properties
            sb.AppendLine("    private void __TriggerOnchange(string fieldName) => TriggerOnchange([fieldName]);");
        }
        else
        {
            // No [Onchange] methods — emit a no-op helper so callers still compile
            sb.AppendLine("    private void __TriggerOnchange(string fieldName) { }");
        }
        sb.AppendLine();
    }

    // ── Stored property helper ─────────────────────────────────────────────

    private static void EmitStoredProperty(StringBuilder sb, FieldDeclaration f, string comment)
    {
        sb.AppendLine($"    // {comment}");
        var nullable = f.IsNullable ? "?" : "";
        var bf = $"_{LowerFirst(f.PropertyName)}";
        sb.AppendLine($"    private {f.TypeName}{nullable} {bf};");
        sb.AppendLine($"    public {f.TypeName}{nullable} {f.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {bf};");
        if (f.HasSetter)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (System.Collections.Generic.EqualityComparer<{f.TypeName}>.Default.Equals({bf}, value)) return;");
            sb.AppendLine($"            {bf} = value;");
            sb.AppendLine($"            OnPropertyChanged(nameof({f.PropertyName}));");
            sb.AppendLine($"            __InvalidateDependents(nameof({f.PropertyName}));");
            sb.AppendLine($"            __TriggerOnchange(nameof({f.PropertyName}));");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Module initializer ─────────────────────────────────────────────────

    private static void EmitModuleInitializer(StringBuilder sb, ResolvedModel model)
    {
        var allParents   = string.Join(", ", model.AllParentNames.Select(p => $"\"{p}\""));
        var delegParents = string.Join(", ", model.DelegationParents.Select(d => $"\"{d.ParentModelName}\""));
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine($"    internal static void __RegisterModel_{Sanitize(model.ModelName)}()");
        sb.AppendLine("        => ModelRegistry.Register(new ModelMeta(");
        sb.AppendLine($"            Name:              \"{model.ModelName}\",");
        sb.AppendLine($"            ClrType:           typeof({model.ClassName}),");
        sb.AppendLine($"            Inherits:          [{allParents}],");
        sb.AppendLine($"            DelegationInherits: [{delegParents}]));");
    }

    // ── Helpers ───────────────────────────────────────────────────────────
    private static string Sanitize(string s) => s.Replace('.', '_').Replace('-', '_');
    private static string LowerFirst(string s) => s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
}
